### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Hot-Tutorials** [Ic0vid/apollo#68]
When is this going to be released

**Comment by Ic0vid** [comment]
Go away u have been blacklisted from client

**Comment by GameGlitz** [comment]
**When is this going to be released?**
_If you believe this question should have not been asked, please end the "project"._

**Comment by Ic0vid** [comment]
> **When is this going to be released?**
> 
> _If you believe this question should have not been asked, please end the "project"._

You say project in quotes like it isn't 10x more successful then anything you have ever done; and I don't have a problem with the question I have a problem with the individual, however that isn't really your business anyway

**Comment by Ic0vid** [comment]
And for anyone wondering the client is actively being worked on now after I took a 2 month break to work on another project

**Comment by GameGlitz** [comment]
First of all - When did GlitzMC release? Ever? You can't bring that up as a point of it being a failure. Plus, you don't even know what I'm working on :joy:, does that network even EXIST ANYMORE?

You cannot talk especially regarding what your client actually is, and deleting my comment is just pwny. Any further responses to this issue **WILL BE IGNORED** by me as I have much better things to do than waste my time on an immature little person 🥇

**Comment by GameGlitz** [comment]
Another thing, you probably don't know my relation to the individual in question there :/

**Comment by Ic0vid** [comment]
Yep this project must be so bad consider you contacted me wanted to be a partner
